### ISSUE TITLE
nom4 release

### ISSUE THREAD

**Issue by kpcyrd** [rusticata/tls-parser#4]
hello! :)

I've successfully ported my application to nom4 using your nom4 branch. Is there anything blocking this branch from being released? Is there any way to help?

Thanks!

**Comment by chifflier** [comment]
Hi,
Most of my parsers (including tls) have been ported to nom4, however I'm still wondering about the 'stable' aspect of the new nom4 API changes (esp. `complete!` is now required everywhere, changing both readability and performances). There are also a few random breakages, like `eof` now returning an error etc. that only manifest at runtime.
I'll run a few more tests before merging into master, and release a new version bumping the version to avoid breaking all rdeps

Pierre

**Comment by kpcyrd** [comment]
@Geal any chance you might be able to have a look at the code as well? This is one of the last major issues to get [sniffglue] into debian. :)

Relevant branches:
https://github.com/rusticata/tls-parser/tree/nom4
https://github.com/rusticata/rusticata-macros/tree/nom4

[sniffglue]: https://github.com/kpcyrd/sniffglue

**Comment by chifflier** [comment]
Hi @kpcyrd ,
tls-parser 0.6.0 has just been released (github & crates.io), with support for nom 4, and a few other changes.
