### ISSUE TITLE
Basic parse_tls_plaintext example does not work

### ISSUE THREAD

**Issue by campbellC** [rusticata/tls-parser#5]
I'm trying out this package and it took me a while to figure out what was wrong with using it. I think the example given in the README no longer works. It looks like the upgrade to nom probably broke it, as IResult is now an alias to a standard result type and so doesn't have the Done enum options.

**Comment by chifflier** [comment]
The README is indeed outdated, I'll fix it (too bad `cargo test` does not build the example).
If needed, you can find more examples in the `tests` subdir, or a more realistic use here: https://github.com/rusticata/rusticata/blob/master/src/tls.rs#L327
