### ISSUE TITLE
Parsers visibility and Nom dependency

### ISSUE THREAD

**Issue by courvoif** [rusticata/tls-parser#7]
Hello,

For a project I need to quickly parse only some Tls records of a session.
So for lessening the amount of alloc, I'd like to be able to parse only a TlsRecordHeader without its data and then only parse the content if needed.
I saw the parse_tls_raw_record functyion but it needs a complete record to work.
What I'd like to write is something like this:

> let data = [0x16, 0x03, 0x01, 0x00, x051];
> let (rem, header) = parse_tls_record_header(&data[..]);
> 
> //Do something with header

I have an other question concerning the Nom dependency this time.
I need to add nom as a dependency in order to use your crate even if I don't use it for anything else.
Wouldn't it be better for your crate to use "pub extern" to reexport the IResult from Nom ?
I know this practice is under [debate](https://github.com/rust-lang/api-guidelines/issues/176) but I think it's very inconvenient to have to pull an entire crate to use an other one.

Thanks for your time

**Comment by chifflier** [comment]
Hi,
Parsing first the header and the record later is possible. You can look at
- this code to read the header: https://github.com/rusticata/rusticata/blob/master/src/tls.rs#L353-L397
- this part to use the header and parse the rest of the record: https://github.com/rusticata/rusticata/blob/master/src/tls.rs#L328-L347

About re-exporting nom, I don't know what's the best practice and if re-exports can cause problems. I need to read more about that. As far as I understand, the only problem with the current situation is that you need to add the same version to your dependencies.

**Comment by courvoif** [comment]
Hi,

Thanks for your answer.

In your examples the buffer needs to contain the record header and its body in order to get the header. What I'd like to do is to be able to parse the header from the buffer even if it doesn't have all the data of the body. I think what I'm looking for is this function: https://github.com/rusticata/tls-parser/blob/master/src/tls.rs#L545-L558

About the re-exporting, it's not really an issue for me because in can always add nom as a dependency but I know some people are reluctant to add new new dep if they don't really need to.

**Comment by courvoif** [comment]
I just found a work around, so I'll close this issue.
Thank you again

**Comment by chifflier** [comment]
Ok, thanks for the update.
There was no real reason to hide these functions, so I have committed some visibility changes, so record header and message parsing functions are now public. This will be part of the next release.
