### ISSUE TITLE
BUG: Incorrect MAX_RECORD_LEN

### ISSUE THREAD

**Issue by devloper** [rusticata/tls-parser#72]
Per the spec, the MAX_RECORD_LEN for _plaintext_ messages should be 1 << 14, however, in the case of ciphertext additional authentication data is needed beyond the max length.  The spec specifies 1 << 14 + 256 as the maximum for encrypted messages. 

Unfortunately the parser produces an error on any messages greater than MAX_RECORD_LEN.   Per my understand of the spec this is a bug and for me it's causing the parser to fail frequently on bulky pages. 

<img width="733" alt="Screen Shot 2024-09-05 at 10 48 33 PM" src="https://github.com/user-attachments/assets/3a94faa5-69ff-476c-8dba-f8de5812da7c">

**Comment by chifflier** [comment]
Hi,
Thank you for your report. Indeed, the code was using max record size for plaintext record, which is incorrect here.
