### ISSUE TITLE
TLS Extension length missing when serializing

### ISSUE THREAD

**Issue by conblem** [rusticata/tls-parser#9]
When serializing a TLSPlaintext Client Hello using the `gen_tls_plaintext` method in Version 0.9.2 the extension length is missing.

In this method https://github.com/rusticata/tls-parser/blob/tls-parser-0.9.2/src/tls.rs#L577 the extension length gets removed and is no longer in the TlsMessageHandshake::ClientHello::ext.
When serializing this member the length should get added back here: https://github.com/rusticata/tls-parser/blob/tls-parser-0.9.2/src/tls_serialize.rs#L184 .

Example on how this could be fixed: https://github.com/rusticata/tls-parser/compare/tls-parser-0.9.2...conblem:fix-tls-client-hello . The current tests sadly did't catch this bug: https://github.com/rusticata/tls-parser/blob/tls-parser-0.9.2/src/tls_serialize.rs#L384 . If i find time I will write a correct test case.

**Comment by chifflier** [comment]
Hi,
Thanks for the report. I'll have a look, to fix this in the stable branch.

However, it may be important to note that the serialization has changed a lot in the current `master` branch (next release). It seems `master` does not have the bug and adds the length correctly.
